Table "houses" {
  "id" int [pk, not null, increment]
  "name" varchar(255) [not null]
}

Table "wizards" {
  "id" int [pk, not null, increment]
  "name" varchar(255) [not null]
  "HouseId" int

  Indexes {
    HouseId [type: btree, name: "HouseId"]
  }
}

Ref "wizards_ibfk_1":"houses"."id" < "wizards"."HouseId" [update: cascade, delete: set null]
