openapi: 3.1.1

info:
  title: Harry Potter API
  version: 1.0.0
  description: |
    Documentation for Harry Potter API
    
    ## CRUD Operations
    ### Path
    - `/api/v1/wizards`
      
    ### Authorisation
    | Authenticated | Role | GET | POST | PUT | DELETE |
    | --- | --- | --- | --- | --- | --- |
    | No | None | Y | N | N | N |
    | Yes | None | Y | Y | N | N |
    | Yes | Admin | Y | Y | Y | Y |

servers: 
  - url: http://localhost:3000/api/v1
    description: Local development server

paths:
  /wizards:
    get:
      tags: 
        - Wizards
      summary: Get a all wizards
      responses:
        "200":
          description: A list of wizards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wizard'
              example: 
                - id: 1
                  name: Harry Potter
                  HouseId: 1
                - id: 2
                  name: Hermione Granger
                  HouseId: 1
                - id: 3
                  name: Ron Weasley
                  HouseId: 1
                - id: 4
                  name: Luna Lovegood
                  HouseId: 3
                - id: 5
                  name: Draco Malfoy
                  HouseId: 4
    post:
      tags: 
        - Wizards
      summary: Create a wizard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWizard'
            example:
              name: Luna Lovegood
      responses:
        "201":
          description: Wizard successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wizard'
              example:
                id: 6
                name: Luna Lovegood
                HouseId: 3
      
  /wizards/{id}:
    put:
      security:
        - BearerAuth: []    
      tags: 
        - Wizards
      parameters: 
      - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWizard'
      responses:
        "204":
          description: Updates a wizard
    delete:
      security:
        - BearerAuth: []
      tags: 
        - Wizards
      parameters: 
      - $ref: '#/components/parameters/id'
      responses:
        "204":
          description: Deletes a wizard

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  parameters:
    id:
      name: id
      in: path
      required: true
      description: A unique identifier for a wizard
      schema:
        type: integer
        example: 1
  schemas:
    Wizard:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Harry Potter
        HouseId:
          type: integer
          example: 1
    CreateWizard:
      type: object
      properties:
        name:
          type: string
          example: Harry Potter
        HouseId:
          type: integer
          example: 1
    UpdateWizard:
      type: object
      properties:
        name:
          type: string
          example: Hermione Grander
        HouseId:
          type: integer
          example: 1